id: P009601
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:40:10.455587
source_metadata:
  id: bdr:W00KG01652
  title: ཡོན་ཏན་གཞིར་གྱུར་མའི་བསྡུས་འགྲེལ་
  author: ''
  volumes:
    e62f8258c512488cb4fbbc4ed49426b6:
      image_group_id: I00KG02963
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
