id: I37FB7E90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:48:40+00:00'
last_modified: '2022-06-08T12:11:09.713362+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01652
  title: ཡོན་ཏན་གཞིར་གྱུར་མའི་བསྡུས་འགྲེལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A558:
      image_group_id: I00KG02963
      title: ''
      total_pages: 110
      order: 1
      base_file: A558.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
