id: I37FB7E90
legacy_id: P009601
ocr_import_info:
  bdrc_scan_id: W00KG01652
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T17:47:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:37:32.768364+00:00'
last_modified: 2022-08-29 19:37:56.257574
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01652
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01652
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡོན་ཏན་གཞིར་གྱུར་མའི་བསྡུས་འགྲེལ།
  author: རྡོ་སྦིས་དགེ་བཤེས་ཤེས་རབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6161557487334345
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I00KG02963:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02963
      total_pages: 110
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02963.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6161557487334345
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
